apiVersion: v1
kind: Secret
metadata: 
  name: mysql
  namespace: roboshop
  labels:
      component: mysql
      project: roboshop
      tier: database
type: opaque
data:
  MYSQL_ROOT_PASSWORD: "Um9ib1Nob3BAMQ=="